
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { AppProvider } from "./components/AppContext";
import { Suspense } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Haylee Graham Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Haylee Graham Portfolio</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-full`}
      >

        <div className="flex flex-col overflow-x-clip min-h-screen">
          <AppProvider>
            <Header />
            <Suspense>
              <main className="flex flex-col lg:w-[95%] w-full self-center">{children}</main>
            </Suspense>
            <Footer />
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
